language: python
python:
  - 3.6
install:
  - pip install -r requirements-dev.txt
script:
  - pytest --pep8 sbg --cov sbg
deploy:
  provider: pypi
  user: sbg
  password:
    secure: oPk4SYBpj7ueanlW8bxbsAYViEFp/f/LruZmNTIuBVYYIWfHFkrlJUUpdBWo39V7hk3VPCb9Ic4CnfggP9a6YPSfdh9cN6n2n505XGV6FUGX28mOKIOnEJ4kN6SLnmHAFacqKRYY7y5RQ+PHccOb9CleR8rkZKvNBz2xYgkEk9UyJfS0nPWEL6M6KndwquoVDxONAO1tFpRk8u5AWW+KQYVpE3h7pIBVW0sJzf6dIxKS7AI61XW+9OTyJ4+bb+tkGKX7yxYnNP8ez4gpP1SEv9yi4nPRR34Ok/9yVcbwccvDKEJRDCVE0jcQuMoFq69bA2OuVG78CWAk6+26YXJ+VcsKSVaHoXxLXMNBwKhHo1smtUEiHzlnTtQd3fZWCFUwCaTG2/6xvKaDBIiK8zg3ZnwdVogcj5zu6rdq0ZNAHvKIZq2sXLkmy3cV7N+9dEz2MhAn516/2+495pIyE5Dg+/ur2JfrJ6Taj0uAcGx1/H4hOpcYFE0YwM7oi6jPEY94CVLj9k11LVJs6imU069Tj5RJD18kt2gz9erA37M0fF4JkLQ8GnclujNKLZWVMQA7MLcGowVdb51vdtsOgWUpfJGqqoQN0A3pzNvadkb+Cm8IieCrXv98/V6jGy+XY407f2j0HAM+Jj5uRfh+klVmrazFJbM9EOq1vNvLyFbBv1Q=
  on:
    tags: true
    branch: develop
    distributions: sdist bdist_wheel
    repo: sbg/sevenbridges-cwl
