language: python
python:
  - 3.6
install:
  - pip install -r requirements-dev.txt
script:
  - pytest --pep8 sbg --cov sbg
deploy:
  provider: pypi
  user: sbg
  password:
    secure: BH65/29DBrpEtnUWrFM2fWiCdq7nzs4XkDd+7sa3wA9Slt3I54Uss8aAG1GtxgY77QpHdSqfFj++UgmLJJ+nUFWlPdb21AniURd4y04+r9QQ6TKE4Yzt3YhVl/59V0fxKHcLGzANoVPncm/vwhfGZDmRKBeLg3qtu/OkA8aVil0nFlnrD5/SXpzbFVN/MV12U/hf/wivRnoSbeM8DRbNR2iy+5dVMfscwDDgXjAiU3DgUQZHz1ArZ3H2GBVKxHFmZDFcZGcB3zO84voAGXInt180GVGyJ68x4QNJI9fSArObHrPkg6j7gDG+ow3b0xLmk7E1NfImF2eHcvvlAhzwurw7lZrRNrynqABaMu9Vgfd1VIMhHWRxuT/B0DB3Jxzd8/0DL6B5ZmrdhvKSIO2SVAMt+M6hM4jUZcVUoV8Uz7PG5FmweQaXf+NWVt7A4iHDgi3d9s79sdjPAhQLCycUNc02ZW4EiZcer85AWq+6e4/4acAWa45Iax9oHyGL4oH51d/AUl8CF0HSQ1dXsIgQ9J2bfXJSQogDuRCL+OkMxSa46qudjXE7d1Uslcyp5NDYoLm+hh+igzAjwKoFYX34EBwIg2B0u0G4dDRTwwYRQlyirxZTp1AX8ykJ0JQA6Rqghuck73YUypwy2rdDoNU5tpAFOd2heLBOMiJj4ePNtMI=
  on:
    tags: true
    branch: develop
    distributions: sdist bdist_wheel
    repo: sbg/sevenbridges-cwl
