language: python

python:
  - 3.6

install:
  - pip install -r requirements-dev.txt

script:
  - pytest --pep8 sbg --cov sbg

deploy:
  provider: pypi
  user: sbg
  password:
    secure: e1GqoX+g6qU88Lfh0PtL4QU3GrNRzzXafiZ395/53hcCm83lNemevxsBJ1CAN2wFpW5Kcjd20Gv6BSFacV8R26cvkSd82iSJvUqbmriIlLS9ro9gRjirZkr8gFV4DhkTbzxojIDAXT5BxNq0xXZF5AaC5eKQCr8ptwXQ77WQTuOZUD+TRgZU/32C77RglX3xeA6xTKqZO4ngg31y+ZHvP+gB/jwwOhzPVrgO9spds04Ve/71+UFI9LR9fJuLzsYIS8ShHtfsSidMb+ofQtGkePEjaEcz3J45D5P2SUedHO+tNuPSWGukG/GU7uGKvnGTbRK5fM+FCIpeKzTtB3N8KqzZCsPEixyrKeVYZZ+TH3RR5K7U4Y9v5dbMoCdtky3uk6+WcT4/al+U18OVJ3MTlBlBIeM6ZQJvi8ZqhE+U80E9RvT/G5JJkMnELoPZ1Wsl0xzAQNtkzgAh3c/pFlPoAW1GJWQh8k5tKqntOyy5Fbs/xJT+95h48LdZqVxfZtJVYqzsQfBlSVxCHqTztiXjuuhISlJIsOork+sltPDFhbbLMig2/FIlK3bfp/qWot8SnF4g8rE2bxm/Ujy9InvFSMQ9sixLOXZf43vEVCq1zLsqg3NO/D/0O5Zb9T0jM/fXcy9ttJAlVDvUHo2IASSAGlA1izpTGlOVSxPxnVjT4IE=
  on:
    tags: true
    branch: develop
    distributions: sdist bdist_wheel
    repo: sbg/sevenbridges-cwl
