language: python
python:
  - 3.6
install:
  - pip install -r requirements-dev.txt
script:
  - pytest --pep8 sbg --cov sbg
deploy:
  provider: pypi
  user: sbg
  password:
    secure: mvsUYOkvVhgQtRiG5qfgbrISW+TUmNQ7uBX0yiR1rEG0hUS4py4SSC9q6vheM2h8uEA/dqlAyRhz0YHpoqk0R7rBwa3CyQbVT6jZNf2W3bKhMn1Run/Im2+GgVnZYMsk4mstZX0yeDyFjQOurUTP/7wA/QvIsf+A6GvZsKUN5TwZbb4tLPsnLfeVHrbzOkV9Y5YVeWyXoS4vzVWPz+33aZVaWpS4zqrtbVh84B+xBLzdyeMHB1hYH37SsIB1Bn3Y7fHREyD+6mVBSFaA9BgAjxZVsEAmPzNvR3UsQoqlj3DeSLdBb234neZwlti7LkntsIKsFjN6mrHpmNAUOokbzKWoRl3vSvyxb+icW6N6FnWlAKV17KdRIizd8+oChHZCAIHAUraaj1ThTXUhlN6yQtTTHBgePw+/z6biNNWiLxleF3kXw5WnuuqxqDIe31P5M9su0hNFbzWa45QwkqI5HKpyYZr/Mbda2MIVKh95/h2ZW6Atu9JKgvF0AspOn+mF2VxAfpU6VjGQijZDnrjyWSRM1/TxVAAs+yiIXRe/z26ZQW8jHWRdYQ3lSG9vjRG2gLWryO3YgjymfeHcI0hNpMEdFv2B+8q9PChtvwzXfMbQLZw0U81kzsovP1QC3gVE6mACxg9dV8HtnnHSKk34a2woHb21WNkWFCcaQtSP24Y=
  on:
    tags: true
    branch: develop
    distributions: sdist bdist_wheel
    repo: sbg/sevenbridges-cwl
