language: python
python:
- 3.9
install:
- pip install -r requirements-dev.txt
script:
- flake8
- pytest --cov
deploy:
  provider: pypi
  user: sbg
  password:
    secure: WXhIFzvKTTV0hfdty6K44uSupTgpubypWAnmYsoF2unJh6+3r0xb6+XfO5R2lzRYk7mxrkywFIYQ7n3iVBEvhNzeUNXldMr7pwP9TwVU01MXZzGuVYGS8J12gZJhT7Doh3XEsWECu1sh4s2vECrVdVSInwB5ZLijwvDtP2lqYprrnJvv6st4hIj/E9Oz+ZMKA2ZvDGdE+i87R++yGIZYROhWr8AMebLU4TbazuN4uPVLTT/qr/mvywJJIi7ujNFdW3UPV9GWeIJJduJLivstsgamtKoiV+rTsYHZReyOhCMeXYSZ74aSnMEEE/7LTce+LRoaAA8ZL9ScZMm7HLEnXisdhyPhbiP61U2fGnK00uJKvu739HBBhH8p9sMxd2KB13ZI4R2hZmuRubHGc7ZWaj/SIuKZsIWhfq9dEUX8oPrCOd1CsvjoD+jkrODSjbY9eUb61nCMiTqLZ/bcEw4N0TINCe11fe934vMgpFxQEa7yTgRoYNwM/R+BAx47nLU8j9z1NuYMV67JU5FVsEWq2DIsaV4ZXMmo2hSdHPxb3gOZEyTMGN0HdTv8j9JKpnznrdo6IYwsPRpbtlvjrWl1LTsC8L5KWgm/xZd1pjNKXfCneQA4BBBX0YQObt7gsfqrcCaku84/jbhmcgH5lGx0YblB+VvBqr6wVAjlWH+lbw8=
  on:
    tags: true
    branch: develop
    distributions: sdist bdist_wheel
    repo: sbg/sevenbridges-cwl
