language: python

python:
  - 3.6

install:
  - pip install -r requirements-dev.txt

script:
  - pytest --pep8 sbg --cov sbg

deploy:
  provider: pypi
  user: sbg
  password:
    secure: PazGG+vLnJvvw+EAt/TXDNHH0505r1d0jQLjJpQJUGF7wi2bbxRPV+EgH+3CRFUrTQORviKIdaR/rvIZGdlFI7rT25T2Im1sUfBk0QT5Ud5zRs7aAd/L5UZONb0Yp51bthwd/gQfNttxyS19XKbdJSiAYEBbPbspxXY3uHrJUcDNGeGkcz5p3vURLruocyqTsoK5iqD4PgrthV9ZRej5bjkEoKw8plDOda9vcCiBbIYUgc2nE4xugefHf7Cb6989VgwjmDZ/YXg6cJhlhxEXHId4sjAyWwa1jUSieD6vNVC58ICh5hD+7GexZeaExA92GxWyoHt7qeR2hAxb78P8W8WW7ARx9xhvRlStsWGCsDNE+hS7VZEdqxXLpiT5GUDBlrUKOsJETbIqcC6l6T5QDTKDGqZtjoNmaeOBMDdLw2adAiH6nU4jfjjDdoc8yGD2emFSq1HvdyNuggRXNy/DKR7PV/ycm7RUcBqKhfWt8ZA021sALHqvas5156cMH7fZzWQ2mI8ILmuIGeVOxzD9/bP9VlsNJEZK5i6BAq6KxkAUgVqm8A+Bk9pCqTCmWX/wuIy8P/w5zaNKGR01BVgBxX/1e9BDoYsPfhZN3vIKX+8y+sRmmzC8Kd1LgGIHU1hB7/eVb6Whnhgz5IupZb2pf/fP8veoTabYZ3xHs7KsXZA=
  on:
    tags: true
    branch: develop
    distributions: sdist bdist_wheel
    repo: sbg/sevenbridges-cwl
